### ISSUE TITLE
Broken responsive styles between 600px and ~1060px

### ISSUE THREAD

**Issue by SWBennett06** [JavaScriptMN/javascriptmn.github.io#19]
Between 600px and ~1060px, several page elements behave poorly:

- The "Next Event" block sits flush with the left side of the window
- The "Location" heading box extends past the left side of the window
- The "Speaking" heading box causes overflow of the main content area

This could be resolved by just broadening the media query for the mobile styling up to 1060px, but may be worth a closer look.

**Comment by BrianMitchL** [comment]
The redesign in #31 should fix this 🙂
