### ISSUE TITLE
Need auto build / deploy when changes merged into build?

### ISSUE THREAD

**Issue by randallmeeker** [JavaScriptMN/javascriptmn.github.io#6]
thoughts

**Comment by skylineproject** [comment]
Yes, we could probably use Travis as this is a public project. https://docs.travis-ci.com/user/deployment

**Comment by skylineproject** [comment]
TravisCI costs money, so maybe not. Running `yarn run deploy` isn't that big of a deal in the meantime. Keeping this issue open in case there are other recommendations for continuous deployment services that are free for public repos on GH orgs.

**Comment by skylineproject** [comment]
Deferred until other infrastructural concerns are ironed out.
